/** Stylelint: order and correctness. Prettier owns whitespace. */
module.exports = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'selector-class-pattern': [
      '^[a-z][a-z0-9]*(-[a-z0-9]+)*(__[a-z0-9]+(-[a-z0-9]+)*)?(--[a-z0-9]+(-[a-z0-9]+)*)?$',
      {
        message: 'Class names follow BEM: block, block__element, block--modifier',
      },
    ],

    /* Prettier owns whitespace; stylelint owns order and correctness. Leaving
       the blank-line rules on means the two rewrite each other forever. */
    'rule-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'number-max-precision': 5,
    'scss/comment-no-empty': null,
    'no-descending-specificity': null,
    'custom-property-empty-line-before': null,
    'declaration-empty-line-before': null,
    'comment-empty-line-before': null,
    'scss/double-slash-comment-empty-line-before': null,

    'order/order': [
      'dollar-variables',
      'custom-properties',
      'declarations',
      { type: 'at-rule', name: 'include' },
      'rules',
      'at-rules',
    ],

    'order/properties-order': [
      [
        {
          groupName: 'layout mode — what kind of box this is',
          properties: [
            'content',
            'display',
            'flex',
            'flex-direction',
            'flex-wrap',
            'flex-basis',
            'flex-grow',
            'flex-shrink',
            'grid-template',
            'grid-template-areas',
            'grid-template-columns',
            'grid-template-rows',
            'grid-area',
            'grid-column',
            'grid-row',
            'place-content',
            'place-items',
            'place-self',
            'align-content',
            'align-items',
            'align-self',
            'justify-content',
            'justify-items',
            'justify-self',
            'gap',
            'row-gap',
            'column-gap',
            'order',
          ],
        },
        {
          groupName: 'position — where it sits',
          properties: [
            'position',
            'inset',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
            'float',
            'clear',
          ],
        },
        {
          groupName: 'size — how much room it takes',
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'aspect-ratio',
            'padding',
            'padding-block',
            'padding-inline',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'margin',
            'margin-block',
            'margin-inline',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'overflow',
            'overflow-x',
            'overflow-y',
            'overscroll-behavior',
            'container',
            'container-type',
            'container-name',
          ],
        },
        {
          groupName: 'type — the text inside',
          properties: [
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'line-height',
            'letter-spacing',
            'text-align',
            'text-decoration',
            'text-overflow',
            'text-wrap',
            'text-transform',
            'white-space',
            'word-break',
            'overflow-wrap',
            'vertical-align',
            'list-style',
            'line-clamp',
            'color',
          ],
        },
        {
          groupName: 'paint — how it looks',
          properties: [
            'background',
            'background-color',
            'background-image',
            'background-size',
            'background-position',
            'background-repeat',
            'fill',
            'stroke',
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-radius',
            'outline',
            'outline-offset',
            'box-shadow',
            'opacity',
            'filter',
            'backdrop-filter',
            'mix-blend-mode',
            'color-scheme',
          ],
        },
        {
          groupName: 'behaviour — how it answers the pointer',
          properties: [
            'appearance',
            'cursor',
            'pointer-events',
            'user-select',
            'touch-action',
            'resize',
            'visibility',
            'object-fit',
            'object-position',
          ],
        },
        {
          groupName: 'motion — what moves, last',
          properties: [
            'transform',
            'transform-origin',
            'transition',
            'transition-property',
            'transition-duration',
            'transition-delay',
            'animation',
            'will-change',
          ],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'never',
      },
    ],
  },
  ignoreFiles: ['dist/**', '.angular/**', 'node_modules/**'],
};
